### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by JuanjoSalvador** [tanukiapp/Sukejuuru#1]
- [x] Add StandardJS linter
- [x] Add Babel ES2015 conversion
- [ ] ~Add Gulp and configure tasks~
- [ ] Add tests
- [x] Publish to NPM

**Comment by JuanjoSalvador** [comment]
Gulp seems a bit overengineering for this purpose.
